version: '1'

services:
  sequrademo-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=sequrademo
      - MYSQL_USER=sequrademo
      - MYSQL_PASSWORD=mysql
    ports:
      - 4306:3306
    volumes:
      - ./dataDb/mysql-data:/var/lib/mysql
    networks:
      - sequrademo-network

  sequrademo-app:
    image: sequrademo:0.0.2
    networks:
      - sequrademo-network
    restart: on-failure
    depends_on:
      - sequerademo-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=sequrademo-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=mysql
      - DATABASE_NAME=sequrademo
      - DATABES_PORT=3306

networks:
  sequrademo-network:

